/**
 * 大杀四方 (Smash Up) - ID 常量定义
 */

export const SMASHUP_ATLAS_IDS = {
    BASE1: 'smashup:base1',
    BASE2: 'smashup:base2',
    BASE3: 'smashup:base3',
    BASE4: 'smashup:base4',
    BASE5: 'smashup:base5',
    BASE6: 'smashup:base6',
    BASE7: 'smashup:base7',
    BASE8: 'smashup:base8',
    BASE9: 'smashup:base9',
    BASE10: 'smashup:base10',
    PRETTY_PRETTY_POD_BASES: 'smashup:pretty-pretty-pod-bases',
    POLYNESIAN_VOYAGERS_BASES: 'smashup:polynesian-voyagers-bases',
    HULUWAWA_BASES: 'smashup:huluwawa-bases',
    PALADIN_BASES: 'smashup:paladin-bases',
    CARDS1: 'smashup:cards1',
    CARDS2: 'smashup:cards2',
    CARDS3: 'smashup:cards3',
    CARDS4: 'smashup:cards4',
    CARDS5: 'smashup:cards5',
    CARDS6: 'smashup:cards6',
    CARDS7: 'smashup:cards7',
    CARDS8: 'smashup:cards8',
    CARDS9: 'smashup:cards9',
    CARDS10: 'smashup:cards10',
    CARDS11: 'smashup:cards11',
    CARDS12: 'smashup:cards12',
    CARDS13: 'smashup:cards13',
    CULTURE_SHOCK_CARDS: 'smashup:culture-shock-cards',
    ITTY_CRITTERS_POD_CARDS: 'smashup:itty-critters-pod-cards',
    KAIJU_POD_CARDS: 'smashup:kaiju-pod-cards',
    TIME_TRAVELERS_POD_CARDS: 'smashup:time-travelers-pod-cards',
    MARVEL_WAVE_ONE_CARDS: 'smashup:marvel-wave-one-cards',
    MARVEL_WAVE_ONE_POD_CARDS: 'smashup:marvel-wave-one-pod-cards',
    MARVEL_VILLAINS_CARDS: 'smashup:marvel-villains-cards',
    MARVEL_VILLAINS_POD_CARDS: 'smashup:marvel-villains-pod-cards',
    KITTY_CATS_POD_CARDS: 'smashup:kitty-cats-pod-cards',
    MYTHIC_HORSES_POD_CARDS: 'smashup:mythic-horses-pod-cards',
    FAIRIES_POD_CARDS: 'smashup:fairies-pod-cards',
    PRINCESSES_POD_CARDS: 'smashup:princesses-pod-cards',
    MERMAIDS_POD_CARDS: 'smashup:mermaids-pod-cards',
    SKELETONS_POD_CARDS: 'smashup:skeletons-pod-cards',
    MYTHIC_GREEKS_POD_CARDS: 'smashup:mythic-greeks-pod-cards',
    SHAPESHIFTERS_POD_CARDS: 'smashup:shapeshifters-pod-cards',
    DRAGONS_POD: 'smashup:dragons-pod',
    DRAGONS_POD_CARDS: 'smashup:dragons-pod',
    SUPERHEROES_POD: 'smashup:superheroes-pod',
    MAGICAL_GIRLS_POD: 'smashup:magical-girls-pod',
    MEGA_TROOPERS_POD: 'smashup:mega-troopers-pod',
    CEASE_AND_DESIST_CARDS: 'smashup:cease-and-desist-cards',
    CEASE_AND_DESIST_BASES: 'smashup:cease-and-desist-bases',
    ASTROKNIGHTS_POD_CARDS: 'smashup:astroknights-pod-cards',
    POLYNESIAN_VOYAGERS_CARDS: 'smashup:polynesian-voyagers-cards',
    PENGUINS_CARDS: 'smashup:penguins-cards',
    PENGUINS_BASES: 'smashup:penguins-bases',
    INTERNATIONAL_INCIDENT_CARDS: 'smashup:international-incident-cards',
    INTERNATIONAL_INCIDENT_BASES: 'smashup:international-incident-bases',
    WHAT_WERE_WE_THINKING_CARDS: 'smashup:what-were-we-thinking-cards',
    WHAT_WERE_WE_THINKING_BASES: 'smashup:what-were-we-thinking-bases',
    DIY_KILLERS_CARDS: 'smashup:diy-killers-cards',
    DIY_KILLERS_BASES: 'smashup:diy-killers-bases',
    DIY_CLOWNS_CARDS: 'smashup:diy-clowns-cards',
    DIY_CLOWNS_BASES: 'smashup:diy-clowns-bases',
    HALF_THE_BATTLE_GECKOS_CARDS: 'smashup:half-the-battle-geckos-cards',
    HALF_THE_BATTLE_GERALD_CARDS: 'smashup:half-the-battle-gerald-cards',
    HALF_THE_BATTLE_COSMOS_CARDS: 'smashup:half-the-battle-cosmos-cards',
    HALF_THE_BATTLE_PEARL_IMAGES_CARDS: 'smashup:half-the-battle-pearl-images-cards',
    HALF_THE_BATTLE_BASES: 'smashup:half-the-battle-bases',
    HULUWAWA_CARDS: 'smashup:huluwawa-cards',
    PALADIN_CARDS: 'smashup:paladin-cards',
    ROUND_TABLE_KNIGHTS_CARDS: 'smashup:round-table-knights-cards',
    ROUND_TABLE_KNIGHTS_BASES: 'smashup:round-table-knights-bases',
    GOBLINS_CARDS: 'smashup:goblins-cards',
    GOBLINS_BASES: 'smashup:goblins-bases',
    MUNCHKIN_DWARVES_CARDS: 'smashup:munchkin-dwarves-cards',
    MUNCHKIN_HALFLINGS_CARDS: 'smashup:munchkin-halflings-cards',
    MUNCHKIN_THIEVES_CARDS: 'smashup:munchkin-thieves-cards',
    MUNCHKIN_MAGES_CARDS: 'smashup:munchkin-mages-cards',
    MUNCHKIN_ELVES_CARDS: 'smashup:munchkin-elves-cards',
    MUNCHKIN_CLERICS_CARDS: 'smashup:munchkin-clerics-cards',
    MUNCHKIN_ORCS_CARDS: 'smashup:munchkin-orcs-cards',
    MUNCHKIN_WARRIORS_CARDS: 'smashup:munchkin-warriors-cards',
    MUNCHKIN_TREASURES_CARDS: 'smashup:munchkin-treasures-cards',
    MUNCHKIN_MONSTERS_CARDS: 'smashup:munchkin-monsters-cards',
    MUNCHKIN_DWARVES_BASES: 'smashup:munchkin-dwarves-bases',
    MUNCHKIN_HALFLINGS_BASES: 'smashup:munchkin-halflings-bases',
    MUNCHKIN_THIEVES_BASES: 'smashup:munchkin-thieves-bases',
    MUNCHKIN_MAGES_BASES: 'smashup:munchkin-mages-bases',
    MUNCHKIN_ELVES_BASES: 'smashup:munchkin-elves-bases',
    MUNCHKIN_CLERICS_BASES: 'smashup:munchkin-clerics-bases',
    MUNCHKIN_ORCS_BASES: 'smashup:munchkin-orcs-bases',
    MUNCHKIN_WARRIORS_BASES: 'smashup:munchkin-warriors-bases',
    HULUWAWA_TITAN: 'smashup:huluwawa-titan',
    PALADIN_TITAN: 'smashup:paladin-titan',
    TITANS: 'smashup:titans',
    SHARKS_POD_CARDS: 'smashup:sharks-pod-cards',
    ALL_STARS_POD_CARDS: 'smashup:all-stars-pod-cards',
    PROMOS_SHEEP_ALL_STARS_CARDS: 'smashup:promos-sheep-all-stars-cards',
    TORNADOS_POD_CARDS: 'smashup:tornados-pod-cards',
    KUNG_FU_FIGHTERS_POD_CARDS: 'smashup:kung-fu-fighters-pod-cards',
    RUSSIAN_FAIRY_TALES_POD_CARDS: 'smashup:russian-fairy-tales-pod-cards',
    ANANSI_TALES_POD_CARDS: 'smashup:anansi-tales-pod-cards',
    EXCELLENT_MOVIES_TEENS_CARDS: 'smashup:excellent-movies-teens-cards',
    EXCELLENT_MOVIES_TEENS_BASES: 'smashup:excellent-movies-teens-bases',
    ACTION_HEROES_POD_CARDS: 'smashup:action-heroes-pod-cards',
    EXPLORERS_POD_CARDS: 'smashup:explorers-pod-cards',
    STAR_ROAMERS_POD_CARDS: 'smashup:star-roamers-pod-cards',
    VIGILANTES_POD_CARDS: 'smashup:vigilantes-pod-cards',
    LUCHADORS_POD_CARDS: 'smashup:luchadors-pod-cards',
    DISNEY_CARDS: 'smashup:disney-cards',
    DISNEY_FOUR_FACTION_CARDS: 'smashup:disney-four-faction-cards',
    DISNEY_FOUR_FACTION_BASES: 'smashup:disney-four-faction-bases',
    DISNEY_BASES: 'smashup:disney-bases',
} as const;

export const SMASHUP_CARD_BACK = {
    type: 'atlas',
    atlasId: SMASHUP_ATLAS_IDS.CARDS2,
    index: 55, // 用户指出 cards2 最后一个索引是卡背 (7x8=56)
} as const;

export const SMASHUP_FACTION_IDS = {
    ACTION_HEROES: 'action_heroes',
    ACTION_HEROES_POD: 'action_heroes_pod',
    AVENGERS: 'avengers',
    BACKTIMERS: 'backtimers',
    SHIELD: 'shield',
    SPIDER_VERSE: 'spider_verse',
    ULTIMATES: 'ultimates',
    HYDRA: 'hydra',
    KREE: 'kree',
    MASTERS_OF_EVIL: 'masters_of_evil',
    SINISTER_SIX: 'sinister_six',
    AVENGERS_POD: 'avengers_pod',
    SHIELD_POD: 'shield_pod',
    SPIDER_VERSE_POD: 'spider_verse_pod',
    ULTIMATES_POD: 'ultimates_pod',
    HYDRA_POD: 'hydra_pod',
    KREE_POD: 'kree_pod',
    MASTERS_OF_EVIL_POD: 'masters_of_evil_pod',
    SINISTER_SIX_POD: 'sinister_six_pod',
    ALADDIN: 'aladdin',
    BEAUTY_AND_THE_BEAST: 'beauty_and_the_beast',
    NIGHTMARE_BEFORE_CHRISTMAS: 'nightmare_before_christmas',
    WRECK_IT_RALPH: 'wreck_it_ralph',
    BIG_HERO_6: 'big_hero_6',
    FROZEN: 'frozen',
    LION_KING: 'lion_king',
    MULAN: 'mulan',
    ALIENS: 'aliens',
    ASTROKNIGHTS: 'astroknights',
    ANCIENT_EGYPTIANS: 'ancient_egyptians',
    ANCIENT_EGYPTIANS_POD: 'ancient_egyptians_pod',
    ANCIENT_INCAS: 'ancient_incas',
    ALIENS_POD: 'aliens_pod',
    ANANSI_TALES: 'anansi_tales',
    ANANSI_TALES_POD: 'anansi_tales_pod',
    COWBOYS: 'cowboys',
    COWBOYS_POD: 'cowboys_pod',
    CHANGERBOTS: 'changerbots',
    DINOSAURS: 'dinosaurs',
    DINOSAURS_POD: 'dinosaurs_pod',
    EXPLORERS: 'explorers',
    EXPLORERS_POD: 'explorers_pod',
    FAIRIES: 'fairies',
    FAIRIES_POD: 'fairies_pod',
    DRAGONS: 'dragons',
    DRAGONS_POD: 'dragons_pod',
    GEEKS: 'geeks',
    ADOLESCENT_EPIC_GECKOS: 'adolescent_epic_geckos',
    GI_GERALD: 'gi_gerald',
    RULERS_OF_THE_COSMOS: 'rulers_of_the_cosmos',
    PEARL_AND_THE_IMAGES: 'pearl_and_the_images',
    KUNG_FU_FIGHTERS: 'kung_fu_fighters',
    VIGILANTES: 'vigilantes',
    VIGILANTES_POD: 'vigilantes_pod',
    TRUCKERS: 'truckers',
    DISCO_DANCERS: 'disco_dancers',
    HULUWAWA: 'huluwawa',
    DIY_KILLERS: 'diy_killers',
    DIY_CLOWNS: 'diy_clowns',
    KITTY_CATS: 'kitty_cats',
    KITTY_CATS_POD: 'kitty_cats_pod',
    MYTHIC_HORSES: 'mythic_horses',
    MYTHIC_HORSES_POD: 'mythic_horses_pod',
    ROUND_TABLE_KNIGHTS: 'round_table_knights',
    GOBLINS: 'goblins',
    MUNCHKIN_DWARVES: 'munchkin_dwarves',
    MUNCHKIN_HALFLINGS: 'munchkin_halflings',
    MUNCHKIN_THIEVES: 'munchkin_thieves',
    MUNCHKIN_MAGES: 'munchkin_mages',
    MUNCHKIN_ELVES: 'munchkin_elves',
    MUNCHKIN_CLERICS: 'munchkin_clerics',
    MUNCHKIN_ORCS: 'munchkin_orcs',
    MUNCHKIN_WARRIORS: 'munchkin_warriors',
    PALADINS: 'paladins',
    PRINCESSES: 'princesses',
    PRINCESSES_POD: 'princesses_pod',
    SHARKS: 'sharks',
    SHARKS_POD: 'sharks_pod',
    TORNADOS: 'tornados',
    TORNADOS_POD: 'tornados_pod',
    MYTHIC_GREEKS: 'mythic_greeks',
    MYTHIC_GREEKS_POD: 'mythic_greeks_pod',
    SHAPESHIFTERS: 'shapeshifters',
    SHAPESHIFTERS_POD: 'shapeshifters_pod',
    CYBORG_APES: 'cyborg_apes',
    GHOSTS: 'ghosts',
    GHOSTS_POD: 'ghosts_pod',
    GRIMMS_FAIRY_TALES: 'grimms_fairy_tales',
    IGNOBLES: 'ignobles',
    ITTY_CRITTERS: 'itty_critters',
    ITTY_CRITTERS_POD: 'itty_critters_pod',
    KAIJU: 'kaiju',
    KAIJU_POD: 'kaiju_pod',
    MAGICAL_GIRLS: 'magical_girls',
    MAGICAL_GIRLS_POD: 'magical_girls_pod',
    MEGA_TROOPERS: 'mega_troopers',
    MEGA_TROOPERS_POD: 'mega_troopers_pod',
    NINJAS: 'ninjas',
    POLYNESIAN_VOYAGERS: 'polynesian_voyagers',
    PENGUINS: 'penguins',
    SUMO_WRESTLERS: 'sumo_wrestlers',
    MUSKETEERS: 'musketeers',
    MOUNTIES: 'mounties',
    LUCHADORS: 'luchadors',
    LUCHADORS_POD: 'luchadors_pod',
    ROCK_STARS: 'rock_stars',
    TEDDY_BEARS: 'teddy_bears',
    GRANNIES: 'grannies',
    PIRATES: 'pirates',
    PIRATES_POD: 'pirates_pod',
    ROBOTS: 'robots',
    ROBOTS_POD: 'robots_pod',
    RUSSIAN_FAIRY_TALES: 'russian_fairy_tales',
    RUSSIAN_FAIRY_TALES_POD: 'russian_fairy_tales_pod',
    SAMURAI: 'samurai',
    SAMURAI_POD: 'samurai_pod',
    STAR_ROAMERS: 'star_roamers',
    STAR_ROAMERS_POD: 'star_roamers_pod',
    SUPER_SPIES: 'super_spies',
    TEENS: 'teens',
    TIME_TRAVELERS: 'time_travelers',
    TIME_TRAVELERS_POD: 'time_travelers_pod',
    TRICKSTERS: 'tricksters',
    TRICKSTERS_POD: 'tricksters_pod',
    VIKINGS: 'vikings',
    VIKINGS_POD: 'vikings_pod',
    WRAITHRUSTLERS: 'wraithrustlers',
    WIZARDS: 'wizards',
    WIZARDS_POD: 'wizards_pod',
    ZOMBIES: 'zombies',
    ZOMBIES_POD: 'zombies_pod',
    BEAR_CAVALRY: 'bear_cavalry',
    BEAR_CAVALRY_POD: 'bear_cavalry_pod',
    STEAMPUNKS: 'steampunks',
    STEAMPUNKS_POD: 'steampunks_pod',
    KILLER_PLANTS: 'killer_plants',
    KILLER_PLANTS_POD: 'killer_plants_pod',
    MINIONS_OF_CTHULHU: 'minions_of_cthulhu',
    MINIONS_OF_CTHULHU_POD: 'minions_of_cthulhu_pod',
    ELDER_THINGS: 'elder_things',
    ELDER_THINGS_POD: 'elder_things_pod',
    EXTRAMORPHS: 'extramorphs',
    INNSMOUTH: 'innsmouth',
    INNSMOUTH_POD: 'innsmouth_pod',
    MISKATONIC_UNIVERSITY: 'miskatonic_university',
    MADNESS: 'madness',
    FRANKENSTEIN: 'frankenstein',
    FRANKENSTEIN_POD: 'frankenstein_pod',
    WEREWOLVES: 'werewolves',
    WEREWOLVES_POD: 'werewolves_pod',
    VAMPIRES: 'vampires',
    VAMPIRES_POD: 'vampires_pod',
    GIANT_ANTS: 'giant_ants',
    GIANT_ANTS_POD: 'giant_ants_pod',
    MERMAIDS: 'mermaids',
    MERMAIDS_POD: 'mermaids_pod',
    SKELETONS: 'skeletons',
    SKELETONS_POD: 'skeletons_pod',
    WORLD_CHAMPS: 'world_champs',
    SHEEP: 'sheep',
    ALL_STARS: 'all_stars',
    ALL_STARS_POD: 'all_stars_pod',
    SUPERHEROES: 'superheroes',
    SUPERHEROES_POD: 'superheroes_pod',
    MISKATONIC_UNIVERSITY_POD: 'miskatonic_university_pod',
    NINJAS_POD: 'ninjas_pod',
} as const;

export type SmashUpFactionId = typeof SMASHUP_FACTION_IDS[keyof typeof SMASHUP_FACTION_IDS];
export type SmashUpFactionImplementationStatus = 'in_progress';

const POD_SUFFIX = '_pod';

export function normalizeFactionSelectionId(factionId: string | null | undefined): string {
    if (typeof factionId !== 'string' || factionId.length === 0) return '';
    return factionId.endsWith(POD_SUFFIX)
        ? factionId.slice(0, -POD_SUFFIX.length)
        : factionId;
}

export function buildFactionSelectionIdentitySet(factionIds: Iterable<string>): Set<string> {
    const identities = new Set<string>();
    for (const factionId of factionIds) {
        const normalizedId = normalizeFactionSelectionId(factionId);
        if (normalizedId) {
            identities.add(normalizedId);
        }
    }
    return identities;
}

export const SMASHUP_FACTION_IMPLEMENTATION_STATUS = {
    [SMASHUP_FACTION_IDS.MUNCHKIN_HALFLINGS]: 'in_progress',
    [SMASHUP_FACTION_IDS.MUNCHKIN_THIEVES]: 'in_progress',
    [SMASHUP_FACTION_IDS.MUNCHKIN_MAGES]: 'in_progress',
    [SMASHUP_FACTION_IDS.MUNCHKIN_ORCS]: 'in_progress',
    [SMASHUP_FACTION_IDS.MUNCHKIN_WARRIORS]: 'in_progress',
    [SMASHUP_FACTION_IDS.DIY_KILLERS]: 'in_progress',
    [SMASHUP_FACTION_IDS.DIY_CLOWNS]: 'in_progress',
    [SMASHUP_FACTION_IDS.SUMO_WRESTLERS]: 'in_progress',
    [SMASHUP_FACTION_IDS.MUSKETEERS]: 'in_progress',
    [SMASHUP_FACTION_IDS.MOUNTIES]: 'in_progress',
    [SMASHUP_FACTION_IDS.LUCHADORS]: 'in_progress',
    [SMASHUP_FACTION_IDS.ANANSI_TALES]: 'in_progress',
    [SMASHUP_FACTION_IDS.GRIMMS_FAIRY_TALES]: 'in_progress',
    [SMASHUP_FACTION_IDS.RUSSIAN_FAIRY_TALES]: 'in_progress',
    [SMASHUP_FACTION_IDS.ANCIENT_INCAS]: 'in_progress',
    [SMASHUP_FACTION_IDS.ADOLESCENT_EPIC_GECKOS]: 'in_progress',
    [SMASHUP_FACTION_IDS.GI_GERALD]: 'in_progress',
    [SMASHUP_FACTION_IDS.RULERS_OF_THE_COSMOS]: 'in_progress',
    [SMASHUP_FACTION_IDS.PEARL_AND_THE_IMAGES]: 'in_progress',
} as const satisfies Partial<Record<SmashUpFactionId, SmashUpFactionImplementationStatus>>;

export const SMASHUP_IN_PROGRESS_FACTION_IDS = new Set<string>(
    Object.entries(SMASHUP_FACTION_IMPLEMENTATION_STATUS)
        .filter(([, status]) => status === 'in_progress')
        .map(([factionId]) => factionId),
);

export const SMASHUP_DIY_FACTION_IDS = new Set<string>([
    SMASHUP_FACTION_IDS.HULUWAWA,
]);

export function isSmashUpDiyFaction(factionId: string | null | undefined): boolean {
    const normalizedId = normalizeFactionSelectionId(factionId);
    return SMASHUP_DIY_FACTION_IDS.has(factionId ?? '')
        || SMASHUP_DIY_FACTION_IDS.has(normalizedId);
}

export function isSmashUpFactionImplementationInProgress(factionId: string): boolean {
    return getSmashUpFactionImplementationStatus(factionId) === 'in_progress';
}

export function getSmashUpFactionImplementationStatus(
    factionId: string | null | undefined,
): SmashUpFactionImplementationStatus | undefined {
    if (typeof factionId !== 'string') return undefined;
    return SMASHUP_FACTION_IMPLEMENTATION_STATUS[factionId as SmashUpFactionId];
}

export function isSmashUpFactionSelectionIdentityImplementationInProgress(factionId: string): boolean {
    const normalizedId = normalizeFactionSelectionId(factionId);
    return isSmashUpFactionImplementationInProgress(factionId)
        || isSmashUpFactionImplementationInProgress(normalizedId);
}

/** 派系中文显示名（domain 层使用，避免依赖 i18n） */
export const FACTION_DISPLAY_NAMES: Record<string, string> = {
    [SMASHUP_FACTION_IDS.ACTION_HEROES]: '动作英雄',
    [SMASHUP_FACTION_IDS.ACTION_HEROES_POD]: '动作英雄 (POD版)',
    [SMASHUP_FACTION_IDS.AVENGERS]: '复仇者',
    [SMASHUP_FACTION_IDS.BACKTIMERS]: '返时者',
    [SMASHUP_FACTION_IDS.AVENGERS_POD]: '复仇者 (POD版)',
    [SMASHUP_FACTION_IDS.SHIELD]: '神盾局',
    [SMASHUP_FACTION_IDS.SHIELD_POD]: '神盾局 (POD版)',
    [SMASHUP_FACTION_IDS.SPIDER_VERSE]: '蜘蛛宇宙',
    [SMASHUP_FACTION_IDS.SPIDER_VERSE_POD]: '蜘蛛宇宙 (POD版)',
    [SMASHUP_FACTION_IDS.ULTIMATES]: '终极战队',
    [SMASHUP_FACTION_IDS.ULTIMATES_POD]: '终极战队 (POD版)',
    [SMASHUP_FACTION_IDS.HYDRA_POD]: '九头蛇 (POD版)',
    [SMASHUP_FACTION_IDS.KREE_POD]: '克里 (POD版)',
    [SMASHUP_FACTION_IDS.MASTERS_OF_EVIL_POD]: '邪恶大师 (POD版)',
    [SMASHUP_FACTION_IDS.SINISTER_SIX_POD]: '邪恶六人组 (POD版)',
    [SMASHUP_FACTION_IDS.ALADDIN]: '阿拉丁',
    [SMASHUP_FACTION_IDS.BEAUTY_AND_THE_BEAST]: '美女与野兽',
    [SMASHUP_FACTION_IDS.NIGHTMARE_BEFORE_CHRISTMAS]: '圣诞夜惊魂',
    [SMASHUP_FACTION_IDS.WRECK_IT_RALPH]: '无敌破坏王',
    [SMASHUP_FACTION_IDS.BIG_HERO_6]: '超能陆战队',
    [SMASHUP_FACTION_IDS.FROZEN]: '冰雪奇缘',
    [SMASHUP_FACTION_IDS.LION_KING]: '狮子王',
    [SMASHUP_FACTION_IDS.MULAN]: '花木兰',
    [SMASHUP_FACTION_IDS.ASTROKNIGHTS]: '宇宙武士',
    [SMASHUP_FACTION_IDS.PIRATES]: '海盗',
    [SMASHUP_FACTION_IDS.PIRATES_POD]: '海盗 (POD版)',
    [SMASHUP_FACTION_IDS.NINJAS]: '忍者',
    [SMASHUP_FACTION_IDS.CHANGERBOTS]: '百变机兵',
    [SMASHUP_FACTION_IDS.DINOSAURS]: '恐龙',
    [SMASHUP_FACTION_IDS.DINOSAURS_POD]: '恐龙 (POD版)',
    [SMASHUP_FACTION_IDS.EXPLORERS]: '探险家',
    [SMASHUP_FACTION_IDS.EXPLORERS_POD]: '探险家 (POD版)',
    [SMASHUP_FACTION_IDS.FAIRIES]: '仙灵',
    [SMASHUP_FACTION_IDS.FAIRIES_POD]: '仙灵 (POD版)',
    [SMASHUP_FACTION_IDS.DRAGONS]: '龙',
    [SMASHUP_FACTION_IDS.DRAGONS_POD]: '龙 (POD版)',
    [SMASHUP_FACTION_IDS.GEEKS]: '极客',
    [SMASHUP_FACTION_IDS.ADOLESCENT_EPIC_GECKOS]: '忍者神龟',
    [SMASHUP_FACTION_IDS.GI_GERALD]: '特种部队杰拉尔德',
    [SMASHUP_FACTION_IDS.RULERS_OF_THE_COSMOS]: '宇宙的巨人希曼',
    [SMASHUP_FACTION_IDS.PEARL_AND_THE_IMAGES]: '珍珠和幻像',
    [SMASHUP_FACTION_IDS.KUNG_FU_FIGHTERS]: '功夫斗士',
    [SMASHUP_FACTION_IDS.VIGILANTES]: '侠义义警',
    [SMASHUP_FACTION_IDS.VIGILANTES_POD]: '侠义义警 (POD版)',
    [SMASHUP_FACTION_IDS.TRUCKERS]: '卡车车神',
    [SMASHUP_FACTION_IDS.DISCO_DANCERS]: '迪厅舞王',
    [SMASHUP_FACTION_IDS.HULUWAWA]: '葫芦娃',
    [SMASHUP_FACTION_IDS.DIY_KILLERS]: '杀人狂',
    [SMASHUP_FACTION_IDS.DIY_CLOWNS]: '小丑',
    [SMASHUP_FACTION_IDS.KITTY_CATS]: '猫咪',
    [SMASHUP_FACTION_IDS.KITTY_CATS_POD]: '猫咪 (POD版)',
    [SMASHUP_FACTION_IDS.MYTHIC_HORSES]: '小马',
    [SMASHUP_FACTION_IDS.MYTHIC_HORSES_POD]: '小马 (POD版)',
    [SMASHUP_FACTION_IDS.ROUND_TABLE_KNIGHTS]: '圆桌骑士',
    [SMASHUP_FACTION_IDS.GOBLINS]: '哥布林',
    [SMASHUP_FACTION_IDS.MUNCHKIN_DWARVES]: '矮人',
    [SMASHUP_FACTION_IDS.MUNCHKIN_HALFLINGS]: '半身人',
    [SMASHUP_FACTION_IDS.MUNCHKIN_THIEVES]: '盗贼',
    [SMASHUP_FACTION_IDS.MUNCHKIN_MAGES]: '法师',
    [SMASHUP_FACTION_IDS.MUNCHKIN_ELVES]: '木精灵',
    [SMASHUP_FACTION_IDS.MUNCHKIN_CLERICS]: '牧师',
    [SMASHUP_FACTION_IDS.MUNCHKIN_ORCS]: '兽人',
    [SMASHUP_FACTION_IDS.MUNCHKIN_WARRIORS]: '勇士',
    [SMASHUP_FACTION_IDS.PALADINS]: '圣骑士',
    [SMASHUP_FACTION_IDS.PRINCESSES]: '公主',
    [SMASHUP_FACTION_IDS.PRINCESSES_POD]: '公主 (POD版)',
    [SMASHUP_FACTION_IDS.SHARKS]: '鲨鱼',
    [SMASHUP_FACTION_IDS.SHARKS_POD]: '鲨鱼 (POD版)',
    [SMASHUP_FACTION_IDS.TORNADOS]: '龙卷风',
    [SMASHUP_FACTION_IDS.TORNADOS_POD]: '龙卷风 (POD版)',
    [SMASHUP_FACTION_IDS.MYTHIC_GREEKS]: '希腊神话',
    [SMASHUP_FACTION_IDS.MYTHIC_GREEKS_POD]: '希腊神话 (POD版)',
    [SMASHUP_FACTION_IDS.SHAPESHIFTERS]: '变形者',
    [SMASHUP_FACTION_IDS.SHAPESHIFTERS_POD]: '变形者 (POD版)',
    [SMASHUP_FACTION_IDS.CYBORG_APES]: '电子猿',
    [SMASHUP_FACTION_IDS.ALIENS]: '外星人',
    [SMASHUP_FACTION_IDS.ALIENS_POD]: '外星人 (POD版)',
    [SMASHUP_FACTION_IDS.ANCIENT_EGYPTIANS]: '古埃及人',
    [SMASHUP_FACTION_IDS.ANCIENT_INCAS]: '古代印加人',
    [SMASHUP_FACTION_IDS.ANANSI_TALES]: '阿南西传说',
    [SMASHUP_FACTION_IDS.ANANSI_TALES_POD]: '阿南西传说 (POD版)',
    [SMASHUP_FACTION_IDS.COWBOYS]: '牛仔',
    [SMASHUP_FACTION_IDS.IGNOBLES]: '卑劣封臣',
    [SMASHUP_FACTION_IDS.ITTY_CRITTERS]: '迷你萌宠',
    [SMASHUP_FACTION_IDS.ITTY_CRITTERS_POD]: '迷你萌宠 (POD版)',
    [SMASHUP_FACTION_IDS.KAIJU]: '怪兽',
    [SMASHUP_FACTION_IDS.KAIJU_POD]: '怪兽 (POD版)',
    [SMASHUP_FACTION_IDS.MAGICAL_GIRLS]: '魔法少女',
    [SMASHUP_FACTION_IDS.MAGICAL_GIRLS_POD]: '魔法少女 (POD版)',
    [SMASHUP_FACTION_IDS.MEGA_TROOPERS]: '超级战队',
    [SMASHUP_FACTION_IDS.MEGA_TROOPERS_POD]: '超级战队 (POD版)',
    [SMASHUP_FACTION_IDS.ROBOTS]: '机器人',
    [SMASHUP_FACTION_IDS.ROBOTS_POD]: '机器人 (POD版)',
    [SMASHUP_FACTION_IDS.RUSSIAN_FAIRY_TALES]: '俄罗斯童话',
    [SMASHUP_FACTION_IDS.RUSSIAN_FAIRY_TALES_POD]: '俄罗斯童话 (POD版)',
    [SMASHUP_FACTION_IDS.SAMURAI]: '武士',
    [SMASHUP_FACTION_IDS.ZOMBIES]: '丧尸',
    [SMASHUP_FACTION_IDS.ZOMBIES_POD]: '丧尸 (POD版)',
    [SMASHUP_FACTION_IDS.VIKINGS]: '维京人',
    [SMASHUP_FACTION_IDS.WIZARDS]: '巫师',
    [SMASHUP_FACTION_IDS.WIZARDS_POD]: '巫师 (POD版)',
    [SMASHUP_FACTION_IDS.TIME_TRAVELERS_POD]: '时间旅行者 (POD版)',
    [SMASHUP_FACTION_IDS.TRICKSTERS]: '捣蛋鬼',
    [SMASHUP_FACTION_IDS.TRICKSTERS_POD]: '捣蛋鬼 (POD版)',
    [SMASHUP_FACTION_IDS.STEAMPUNKS]: '蒸汽朋克',
    [SMASHUP_FACTION_IDS.STEAMPUNKS_POD]: '蒸汽朋克 (POD版)',
    [SMASHUP_FACTION_IDS.GHOSTS]: '幽灵',
    [SMASHUP_FACTION_IDS.GHOSTS_POD]: '幽灵 (POD版)',
    [SMASHUP_FACTION_IDS.GRIMMS_FAIRY_TALES]: '格林童话',
    [SMASHUP_FACTION_IDS.KILLER_PLANTS]: '食人花',
    [SMASHUP_FACTION_IDS.KILLER_PLANTS_POD]: '食人花 (POD版)',
    [SMASHUP_FACTION_IDS.POLYNESIAN_VOYAGERS]: '波利尼西亚航海者',
    [SMASHUP_FACTION_IDS.PENGUINS]: '企鹅',
    [SMASHUP_FACTION_IDS.SUMO_WRESTLERS]: '相扑手',
    [SMASHUP_FACTION_IDS.MUSKETEERS]: '火枪手',
    [SMASHUP_FACTION_IDS.MOUNTIES]: '骑警',
    [SMASHUP_FACTION_IDS.LUCHADORS]: '摔角手',
    [SMASHUP_FACTION_IDS.LUCHADORS_POD]: '摔角手 (POD版)',
    [SMASHUP_FACTION_IDS.ROCK_STARS]: '摇滚明星',
    [SMASHUP_FACTION_IDS.TEDDY_BEARS]: '泰迪熊',
    [SMASHUP_FACTION_IDS.GRANNIES]: '外婆',
    [SMASHUP_FACTION_IDS.BEAR_CAVALRY]: '熊骑兵',
    [SMASHUP_FACTION_IDS.BEAR_CAVALRY_POD]: '熊骑兵 (POD版)',
    [SMASHUP_FACTION_IDS.MINIONS_OF_CTHULHU]: '克苏鲁仆从',
    [SMASHUP_FACTION_IDS.MINIONS_OF_CTHULHU_POD]: '克苏鲁仆从 (POD版)',
    [SMASHUP_FACTION_IDS.ELDER_THINGS]: '远古物种',
    [SMASHUP_FACTION_IDS.ELDER_THINGS_POD]: '远古物种 (POD版)',
    [SMASHUP_FACTION_IDS.EXTRAMORPHS]: '异形变体',
    [SMASHUP_FACTION_IDS.INNSMOUTH]: '印斯茅斯',
    [SMASHUP_FACTION_IDS.INNSMOUTH_POD]: '印斯茅斯 (POD版)',
    [SMASHUP_FACTION_IDS.MISKATONIC_UNIVERSITY]: '米斯卡塔尼克',
    [SMASHUP_FACTION_IDS.MADNESS]: '疯狂',
    [SMASHUP_FACTION_IDS.FRANKENSTEIN]: '科学怪人',
    [SMASHUP_FACTION_IDS.FRANKENSTEIN_POD]: '科学怪人 (POD版)',
    [SMASHUP_FACTION_IDS.WEREWOLVES]: '狼人',
    [SMASHUP_FACTION_IDS.WEREWOLVES_POD]: '狼人 (POD版)',
    [SMASHUP_FACTION_IDS.VAMPIRES]: '吸血鬼',
    [SMASHUP_FACTION_IDS.VAMPIRES_POD]: '吸血鬼 (POD版)',
    [SMASHUP_FACTION_IDS.GIANT_ANTS]: '巨蚁',
    [SMASHUP_FACTION_IDS.GIANT_ANTS_POD]: '巨蚁 (POD版)',
    [SMASHUP_FACTION_IDS.MERMAIDS]: '美人鱼',
    [SMASHUP_FACTION_IDS.MERMAIDS_POD]: '美人鱼 (POD版)',
    [SMASHUP_FACTION_IDS.SKELETONS]: '骷髅',
    [SMASHUP_FACTION_IDS.SKELETONS_POD]: '骷髅 (POD版)',
    [SMASHUP_FACTION_IDS.WORLD_CHAMPS]: '世界冠军',
    [SMASHUP_FACTION_IDS.SHEEP]: '绵羊',
    [SMASHUP_FACTION_IDS.ALL_STARS]: '全明星',
    [SMASHUP_FACTION_IDS.ALL_STARS_POD]: '全明星 (POD版)',
    [SMASHUP_FACTION_IDS.SUPERHEROES]: '超级英雄',
    [SMASHUP_FACTION_IDS.SUPERHEROES_POD]: '超级英雄 (POD版)',
    [SMASHUP_FACTION_IDS.MISKATONIC_UNIVERSITY_POD]: '米斯卡塔尼克 (POD版)',
    [SMASHUP_FACTION_IDS.NINJAS_POD]: '忍者 (POD版)',
    [SMASHUP_FACTION_IDS.SUPER_SPIES]: '超级间谍',
    [SMASHUP_FACTION_IDS.STAR_ROAMERS]: '星际旅者',
    [SMASHUP_FACTION_IDS.TEENS]: '青少年',
    [SMASHUP_FACTION_IDS.STAR_ROAMERS_POD]: '星际旅者 (POD版)',
    [SMASHUP_FACTION_IDS.TIME_TRAVELERS]: '时间旅行者',
    [SMASHUP_FACTION_IDS.TIME_TRAVELERS_POD]: '时间旅行者 (POD版)',
    [SMASHUP_FACTION_IDS.WRAITHRUSTLERS]: '怨灵捕手',
};

FACTION_DISPLAY_NAMES[SMASHUP_FACTION_IDS.ANCIENT_EGYPTIANS_POD] = '古埃及人 (POD版)';
FACTION_DISPLAY_NAMES[SMASHUP_FACTION_IDS.COWBOYS_POD] = '牛仔 (POD版)';
FACTION_DISPLAY_NAMES[SMASHUP_FACTION_IDS.SAMURAI_POD] = '武士 (POD版)';
FACTION_DISPLAY_NAMES[SMASHUP_FACTION_IDS.VIKINGS_POD] = '维京人 (POD版)';
